
import { Exercise, Muscle } from './types';

export const ALL_MUSCLES: Muscle[] = Object.values(Muscle);

export const EXERCISE_LIBRARY: Exercise[] = [
  // PUSH
  {
    id: "ex02",
    name: "Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Pectoralis, percentage: 86 },
      { muscle: Muscle.Triceps, percentage: 15 },
      { muscle: Muscle.Deltoids, percentage: 24 },
    ],
    variation: "A",
  },
  {
    id: "ex38",
    name: "Single Arm Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Pectoralis, percentage: 85 },
      { muscle: Muscle.Triceps, percentage: 15 },
      { muscle: Muscle.Deltoids, percentage: 24 },
      { muscle: Muscle.Core, percentage: 35 },
    ],
    variation: "Both",
  },
  {
    id: "ex03",
    name: "Push-up",
    category: "Push",
    equipment: ["Bodyweight", "Pull-up Bar"],
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 75 },
        { muscle: Muscle.Triceps, percentage: 75 },
        { muscle: Muscle.Deltoids, percentage: 30 },
        { muscle: Muscle.Core, percentage: 35 },
    ],
    variation: "B",
  },
   {
    id: "ex05",
    name: "Dumbbell Shoulder Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Deltoids, percentage: 63 },
        { muscle: Muscle.Pectoralis, percentage: 30 },
        { muscle: Muscle.Triceps, percentage: 40 },
    ],
    variation: "B",
  },

  // PULL
  {
    id: "ex06",
    name: "Pull-up",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Lats, percentage: 120 },
      { muscle: Muscle.Biceps, percentage: 87 },
      { muscle: Muscle.Rhomboids, percentage: 50 },
      { muscle: Muscle.Forearms, percentage: 25 },
    ],
    variation: "Both",
  },
  {
    id: "ex07",
    name: "Dumbbell Bicep Curl",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Biceps, percentage: 72 },
      { muscle: Muscle.Forearms, percentage: 15 },
    ],
    variation: "Both",
  },
  {
    id: "ex09",
    name: "Dumbbell Row",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 55 },
        { muscle: Muscle.Trapezius, percentage: 50 },
        { muscle: Muscle.Rhomboids, percentage: 50 },
        { muscle: Muscle.Biceps, percentage: 30 },
    ],
    variation: "B",
  },

  // LEGS
  {
    id: "ex12",
    name: "Kettlebell Goblet Squat",
    category: "Legs",
    equipment: "Kettlebell",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Quadriceps, percentage: 72 },
      { muscle: Muscle.Glutes, percentage: 65 },
      { muscle: Muscle.Hamstrings, percentage: 35 },
      { muscle: Muscle.Core, percentage: 30 },
    ],
    variation: "A",
  },
   {
    id: "ex13",
    name: "Dumbbell Romanian Deadlift",
    category: "Legs",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Hamstrings, percentage: 75 },
      { muscle: Muscle.Glutes, percentage: 55 },
      { muscle: Muscle.Core, percentage: 40 },
    ],
    variation: "B",
  },
  {
    id: "ex15",
    name: "Calf Raises",
    category: "Legs",
    equipment: ["Bodyweight", "Dumbbells"],
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Calves, percentage: 51 },
    ],
    variation: "A",
  },

  // CORE
  {
    id: "ex16",
    name: "Plank",
    category: "Core",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Core, percentage: 77 },
      { muscle: Muscle.Deltoids, percentage: 20 },
    ],
    variation: "Both",
  },
  {
    id: "ex17",
    name: "Bench Sit-ups",
    category: "Core",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Core, percentage: 70 },
    ],
    variation: "A",
  },
  // NEW PULL/BACK
  {
    id: "ex18",
    name: "Dumbbell Upright Row",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Trapezius, percentage: 70 },
        { muscle: Muscle.Deltoids, percentage: 65 },
        { muscle: Muscle.Biceps, percentage: 30 },
    ],
    variation: "Both",
  },
  {
    id: "ex19",
    name: "TRX Bicep Curl",
    category: "Pull",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Biceps, percentage: 65 },
        { muscle: Muscle.Core, percentage: 25 },
    ],
    variation: "Both",
  },
  {
    id: "ex20",
    name: "Chin-Ups",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 120 },
        { muscle: Muscle.Biceps, percentage: 87 },
        { muscle: Muscle.Pectoralis, percentage: 51 },
    ],
    variation: "Both",
  },
  {
    id: "ex21",
    name: "Face Pull",
    category: "Pull",
    equipment: "TRX",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Deltoids, percentage: 55 },
        { muscle: Muscle.Trapezius, percentage: 55 },
        { muscle: Muscle.Rhomboids, percentage: 55 },
    ],
    variation: "Both",
  },
  {
    id: "ex22",
    name: "Concentration Curl",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Biceps, percentage: 85 },
    ],
    variation: "A",
  },
  {
    id: "ex23",
    name: "Shoulder Shrugs",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [{ muscle: Muscle.Trapezius, percentage: 75 }],
    variation: "Both",
  },
  {
    id: "ex25",
    name: "Incline Hammer Curl",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Biceps, percentage: 70 },
        { muscle: Muscle.Forearms, percentage: 30 },
    ],
    variation: "Both",
  },
  {
    id: "ex26",
    name: "Neutral Grip Pull-ups",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 120 },
        { muscle: Muscle.Biceps, percentage: 87 },
        { muscle: Muscle.Trapezius, percentage: 37 },
    ],
    variation: "Both",
  },
  {
    id: "ex28",
    name: "Renegade Rows",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 60 },
        { muscle: Muscle.Core, percentage: 80 },
        { muscle: Muscle.Rhomboids, percentage: 60 },
        { muscle: Muscle.Pectoralis, percentage: 30 },
    ],
    variation: "Both",
  },
  {
    id: "ex41",
    name: "TRX Pull-up",
    category: "Pull",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 115 },
        { muscle: Muscle.Biceps, percentage: 87 },
        { muscle: Muscle.Core, percentage: 30 },
        { muscle: Muscle.Forearms, percentage: 35 },
    ],
    variation: "Both",
  },
  {
    id: "ex42",
    name: "Wide Grip Pull-ups",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 124 },
        { muscle: Muscle.Biceps, percentage: 78 },
        { muscle: Muscle.Trapezius, percentage: 60 },
        { muscle: Muscle.Rhomboids, percentage: 20 },
    ],
    variation: "A",
  },
  // NEW PUSH
  {
    id: "ex29",
    name: "TRX Reverse Flys",
    category: "Push",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Deltoids, percentage: 60 },
        { muscle: Muscle.Trapezius, percentage: 40 },
        { muscle: Muscle.Rhomboids, percentage: 40 },
    ],
    variation: "Both",
  },
  {
    id: "ex30",
    name: "Tricep Extension",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [{ muscle: Muscle.Triceps, percentage: 77 }],
    variation: "A",
  },
  {
    id: "ex40",
    name: "TRX Tricep Extension",
    category: "Push",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Triceps, percentage: 60 },
      { muscle: Muscle.Core, percentage: 25 },
    ],
    variation: "Both",
  },
  {
    id: "ex31",
    name: "TRX Pushup",
    category: "Push",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 109 },
        { muscle: Muscle.Triceps, percentage: 42 },
        { muscle: Muscle.Deltoids, percentage: 50 },
        { muscle: Muscle.Core, percentage: 40 },
    ],
    variation: "Both", // A/B in spreadsheet
  },
  {
    id: "ex32",
    name: "Incline Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 29 },
        { muscle: Muscle.Triceps, percentage: 15 },
        { muscle: Muscle.Deltoids, percentage: 32 },
    ],
    variation: "B",
  },
  {
    id: "ex39",
    name: "Single Arm Incline Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 29 },
        { muscle: Muscle.Triceps, percentage: 15 },
        { muscle: Muscle.Deltoids, percentage: 32 },
        { muscle: Muscle.Core, percentage: 35 },
    ],
    variation: "Both",
  },
  {
    id: "ex33",
    name: "Dips",
    category: "Push",
    equipment: "Dip Station",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Triceps, percentage: 88 },
        { muscle: Muscle.Pectoralis, percentage: 80 },
        { muscle: Muscle.Deltoids, percentage: 40 },
    ],
    variation: "B",
  },
  {
    id: "ex34",
    name: "Kettlebell Press",
    category: "Push",
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Deltoids, percentage: 58 },
        { muscle: Muscle.Pectoralis, percentage: 30 },
        { muscle: Muscle.Core, percentage: 25 },
    ],
    variation: "Both",
  },
  // NEW LEGS
  {
    id: "ex35",
    name: "Glute Bridges",
    category: "Legs",
    equipment: ["Bodyweight", "Dumbbells"],
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Glutes, percentage: 76 },
        { muscle: Muscle.Hamstrings, percentage: 23 },
    ],
    variation: "B",
  },
  {
    id: "ex36",
    name: "Dumbbell Stiff Legged Deadlift",
    category: "Legs",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Glutes, percentage: 70 },
        { muscle: Muscle.Hamstrings, percentage: 65 },
        { muscle: Muscle.Core, percentage: 50 },
    ],
    variation: "B",
  },
  {
    id: "ex37",
    name: "Kettlebell Swings",
    category: "Legs",
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Glutes, percentage: 75 },
        { muscle: Muscle.Hamstrings, percentage: 90 },
        { muscle: Muscle.Core, percentage: 40 },
    ],
    variation: "Both",
  },
  {
    id: "ex43",
    name: "Dumbbell Goblet Squat",
    category: "Legs",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Quadriceps, percentage: 72 },
        { muscle: Muscle.Glutes, percentage: 65 },
        { muscle: Muscle.Hamstrings, percentage: 35 },
        { muscle: Muscle.Core, percentage: 30 },
    ],
    variation: "Both",
  },
  {
    id: "ex44",
    name: "Spider Planks",
    category: "Core",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Core, percentage: 90 },
        { muscle: Muscle.Deltoids, percentage: 20 },
    ],
    variation: "Both",
  },
  {
    id: "ex45",
    name: "TRX Mountain Climbers",
    category: "Core",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Core, percentage: 70 },
        { muscle: Muscle.Deltoids, percentage: 30 },
    ],
    variation: "Both",
  },
  {
    id: "ex46",
    name: "Hanging Leg Raises",
    category: "Core",
    equipment: "Pull-up Bar",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Core, percentage: 75 },
        { muscle: Muscle.Forearms, percentage: 15 },
    ],
    variation: "Both",
  },
  {
    id: "ex47",
    name: "Box Step-ups",
    category: "Legs",
    equipment: "Plyo Box",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Quadriceps, percentage: 67 },
        { muscle: Muscle.Glutes, percentage: 169 },
        { muscle: Muscle.Hamstrings, percentage: 51 },
        { muscle: Muscle.Calves, percentage: 20 },
        { muscle: Muscle.Core, percentage: 15 },
    ],
    variation: "B",
  },
  {
    id: "ex48",
    name: "Dumbbell Pullover",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 60 },
        { muscle: Muscle.Pectoralis, percentage: 40 },
        { muscle: Muscle.Triceps, percentage: 35 },
    ],
    variation: "Both",
  },
];