import { Exercise, Muscle, DetailedMuscle } from './types';

export const ALL_MUSCLES: Muscle[] = Object.values(Muscle);

export const EXERCISE_LIBRARY: Exercise[] = [
  // PUSH
  {
    id: "ex02",
    name: "Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Pectoralis, percentage: 85 },
      { muscle: Muscle.Triceps, percentage: 35 },
      { muscle: Muscle.Deltoids, percentage: 35 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 85.7, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 60, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 26, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 15, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 15, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 15, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
    ],
    variation: "A",
  },
  {
    id: "ex38",
    name: "Single Arm Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Pectoralis, percentage: 80 },
      { muscle: Muscle.Triceps, percentage: 35 },
      { muscle: Muscle.Deltoids, percentage: 35 },
      { muscle: Muscle.Core, percentage: 25 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 85, role: 'primary', citation: 'Estimated from unilateral pressing research' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 60, role: 'secondary', citation: 'Estimated from unilateral pressing research' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 26, role: 'secondary', citation: 'Estimated from unilateral pressing research' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 15, role: 'secondary', citation: 'Estimated from unilateral pressing research' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 15, role: 'secondary', citation: 'Estimated from unilateral pressing research' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 15, role: 'secondary', citation: 'Estimated from unilateral pressing research' },
      { muscle: DetailedMuscle.ExternalObliques, percentage: 35, role: 'secondary', citation: 'Anti-rotation core activation' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 35, role: 'secondary', citation: 'Anti-rotation core activation' },
    ],
    variation: "Both",
  },
  {
    id: "ex03",
    name: "Push-up",
    category: "Push",
    equipment: ["Bodyweight", "Pull-up Bar"],
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 70 },
        { muscle: Muscle.Triceps, percentage: 50 },
        { muscle: Muscle.Deltoids, percentage: 40 },
        { muscle: Muscle.Core, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 75, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 70, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 75, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 75, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 75, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 30, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.SerratusAnterior, percentage: 45, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 35, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020' },
    ],
    variation: "B",
  },
   {
    id: "ex05",
    name: "Dumbbell Shoulder Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Deltoids, percentage: 80 },
        { muscle: Muscle.Triceps, percentage: 40 },
        { muscle: Muscle.Trapezius, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 63.3, role: 'primary', citation: 'Saeterbakken et al., 2015' },
      { muscle: DetailedMuscle.MedialDeltoid, percentage: 30.3, role: 'secondary', citation: 'Campos et al., 2020' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 30, role: 'secondary', citation: 'Saeterbakken et al., 2015' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 40, role: 'secondary', citation: 'Estimated from overhead pressing' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 40, role: 'secondary', citation: 'Estimated from overhead pressing' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 40, role: 'secondary', citation: 'Estimated from overhead pressing' },
      { muscle: DetailedMuscle.UpperTrapezius, percentage: 20, role: 'secondary', citation: 'Scapular elevation' },
      { muscle: DetailedMuscle.Supraspinatus, percentage: 15, role: 'stabilizer', citation: 'Rotator cuff stabilization' },
      { muscle: DetailedMuscle.Infraspinatus, percentage: 15, role: 'stabilizer', citation: 'Rotator cuff stabilization' },
    ],
    variation: "B",
  },

  // PULL
  {
    id: "ex06",
    name: "Pull-up",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Lats, percentage: 85 },
      { muscle: Muscle.Biceps, percentage: 30 },
      { muscle: Muscle.Rhomboids, percentage: 20 },
      { muscle: Muscle.Forearms, percentage: 25 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 123, role: 'primary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 87, role: 'primary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.Brachialis, percentage: 70, role: 'primary', citation: 'Estimated from pull-up mechanics' },
      { muscle: DetailedMuscle.Infraspinatus, percentage: 75, role: 'primary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.LowerTrapezius, percentage: 50, role: 'secondary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 50, role: 'secondary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 30, role: 'secondary', citation: 'Forearm activation' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 25, role: 'secondary', citation: 'Grip strength' },
    ],
    variation: "Both",
  },
  {
    id: "ex07",
    name: "Dumbbell Bicep Curl",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Biceps, percentage: 80 },
      { muscle: Muscle.Forearms, percentage: 15 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 72, role: 'primary', citation: 'Multiple bicep curl EMG studies' },
      { muscle: DetailedMuscle.Brachialis, percentage: 60, role: 'secondary', citation: 'Elbow flexion synergist' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 35, role: 'secondary', citation: 'Forearm flexion' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 15, role: 'stabilizer', citation: 'Grip stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex09",
    name: "Dumbbell Row",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 75 },
        { muscle: Muscle.Biceps, percentage: 20 },
        { muscle: Muscle.Rhomboids, percentage: 35 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 55, role: 'primary', citation: 'Youdas et al., 2010; General rowing EMG' },
      { muscle: DetailedMuscle.RhomboidsDetailed, percentage: 50, role: 'primary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 45, role: 'secondary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 35, role: 'secondary', citation: 'Elbow flexion' },
      { muscle: DetailedMuscle.Brachialis, percentage: 30, role: 'secondary', citation: 'Elbow flexion synergist' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 25, role: 'secondary', citation: 'Forearm activation' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 20, role: 'stabilizer', citation: 'Spinal stabilization' },
    ],
    variation: "B",
  },

  // LEGS
  {
    id: "ex12",
    name: "Kettlebell Goblet Squat",
    category: "Legs",
    equipment: "Kettlebell",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Quadriceps, percentage: 85 },
      { muscle: Muscle.Glutes, percentage: 65 },
      { muscle: Muscle.Core, percentage: 30 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.VastusLateralis, percentage: 76.4, role: 'primary', citation: 'Systematic review, 2024' },
      { muscle: DetailedMuscle.VastusMedialis, percentage: 67.8, role: 'primary', citation: 'Systematic review, 2024' },
      { muscle: DetailedMuscle.VastusIntermedius, percentage: 65, role: 'primary', citation: 'Estimated from quad mechanics' },
      { muscle: DetailedMuscle.RectusFemoris, percentage: 70, role: 'primary', citation: 'Hip flexor and knee extensor' },
      { muscle: DetailedMuscle.GluteusMaximus, percentage: 65, role: 'primary', citation: 'Estimated moderate-high' },
      { muscle: DetailedMuscle.GluteusMedius, percentage: 40, role: 'secondary', citation: 'Hip stabilization' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 30, role: 'stabilizer', citation: 'Core stabilization' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 25, role: 'stabilizer', citation: 'Spinal stabilization' },
    ],
    variation: "A",
  },
   {
    id: "ex13",
    name: "Dumbbell Romanian Deadlift",
    category: "Legs",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Hamstrings, percentage: 85 },
      { muscle: Muscle.Glutes, percentage: 60 },
      { muscle: Muscle.Core, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.Semitendinosus, percentage: 75, role: 'primary', citation: 'Martín-Fuentes et al., 2020 (higher than biceps femoris)' },
      { muscle: DetailedMuscle.Semimembranosus, percentage: 70, role: 'primary', citation: 'Medial hamstring activation' },
      { muscle: DetailedMuscle.BicepsFemoris, percentage: 65, role: 'primary', citation: 'Coratella et al., 2022' },
      { muscle: DetailedMuscle.GluteusMaximus, percentage: 50, role: 'secondary', citation: 'Coratella et al., 2022 (lower than conventional DL)' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 40, role: 'secondary', citation: 'Martín-Fuentes et al., 2020' },
      { muscle: DetailedMuscle.GluteusMedius, percentage: 30, role: 'stabilizer', citation: 'Hip stabilization' },
    ],
    variation: "B",
  },
  {
    id: "ex15",
    name: "Calf Raises",
    category: "Legs",
    equipment: ["Bodyweight", "Dumbbells"],
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Calves, percentage: 95 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.GastrocnemiusMedial, percentage: 51, role: 'primary', citation: 'Soares et al., 2020; André et al., 2021' },
      { muscle: DetailedMuscle.GastrocnemiusLateral, percentage: 50, role: 'primary', citation: 'Soares et al., 2020; André et al., 2021' },
      { muscle: DetailedMuscle.Soleus, percentage: 51, role: 'primary', citation: 'Soares et al., 2020; André et al., 2021' },
    ],
    variation: "A",
  },

  // CORE
  {
    id: "ex16",
    name: "Plank",
    category: "Core",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Core, percentage: 90 },
      { muscle: Muscle.Deltoids, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.ExternalObliques, percentage: 103, role: 'primary', citation: 'Recent EMG analysis, 2025' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 81, role: 'primary', citation: 'Recent EMG analysis, 2025' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 53, role: 'primary', citation: 'Recent EMG analysis, 2025 (right side)' },
      { muscle: DetailedMuscle.TransverseAbdominis, percentage: 50, role: 'primary', citation: 'Deep core stabilization' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 23, role: 'stabilizer', citation: 'Recent EMG analysis, 2025' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 20, role: 'stabilizer', citation: 'Shoulder stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex17",
    name: "Bench Sit-ups",
    category: "Core",
    equipment: "Bodyweight",
    difficulty: "Beginner",
    muscleEngagements: [
      { muscle: Muscle.Core, percentage: 85 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 70, role: 'primary', citation: 'Estimated 60-80% MVIC' },
      { muscle: DetailedMuscle.Iliopsoas, percentage: 65, role: 'primary', citation: 'High hip flexor engagement from leg suspension' },
      { muscle: DetailedMuscle.ExternalObliques, percentage: 50, role: 'secondary', citation: 'Estimated 40-60% MVIC' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 45, role: 'secondary', citation: 'Core stabilization' },
    ],
    variation: "A",
  },
  // NEW PULL/BACK
  {
    id: "ex18",
    name: "Dumbbell Upright Row",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Trapezius, percentage: 60 },
        { muscle: Muscle.Deltoids, percentage: 40 },
        { muscle: Muscle.Biceps, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.UpperTrapezius, percentage: 65, role: 'primary', citation: 'McAllister et al., 2013' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 55, role: 'primary', citation: 'McAllister et al., 2013' },
      { muscle: DetailedMuscle.MedialDeltoid, percentage: 50, role: 'primary', citation: 'McAllister et al., 2013' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 40, role: 'secondary', citation: 'Scapular elevation' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 25, role: 'secondary', citation: 'McAllister et al., 2013' },
      { muscle: DetailedMuscle.Brachialis, percentage: 20, role: 'secondary', citation: 'Elbow flexion support' },
      { muscle: DetailedMuscle.LevatorScapulae, percentage: 20, role: 'stabilizer', citation: 'Scapular elevation' },
    ],
    variation: "Both",
  },
  {
    id: "ex19",
    name: "TRX Bicep Curl",
    category: "Pull",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Biceps, percentage: 80 },
        { muscle: Muscle.Forearms, percentage: 15 },
        { muscle: Muscle.Core, percentage: 15 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 70, role: 'primary', citation: 'TRX variation estimated' },
      { muscle: DetailedMuscle.Brachialis, percentage: 60, role: 'secondary', citation: 'Elbow flexion synergist' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 30, role: 'secondary', citation: 'Forearm activation' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 20, role: 'stabilizer', citation: 'Core stabilization' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 15, role: 'stabilizer', citation: 'Grip stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex20",
    name: "Chin-Ups",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 85 },
        { muscle: Muscle.Biceps, percentage: 30 },
        { muscle: Muscle.Rhomboids, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 123, role: 'primary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 96, role: 'primary', citation: 'Youdas et al., 2010 (higher than pull-ups)' },
      { muscle: DetailedMuscle.Brachialis, percentage: 75, role: 'primary', citation: 'Enhanced elbow flexion with supinated grip' },
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 57, role: 'secondary', citation: 'Youdas et al., 2010 (higher than pull-ups)' },
      { muscle: DetailedMuscle.LowerTrapezius, percentage: 50, role: 'secondary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 30, role: 'secondary', citation: 'Forearm activation' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 25, role: 'secondary', citation: 'Grip strength' },
    ],
    variation: "Both",
  },
  {
    id: "ex21",
    name: "Face Pull",
    category: "Pull",
    equipment: "TRX",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Trapezius, percentage: 70 },
        { muscle: Muscle.Rhomboids, percentage: 60 },
        { muscle: Muscle.Deltoids, percentage: 30 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PosteriorDeltoid, percentage: 60, role: 'primary', citation: 'Face pull biomechanics' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 55, role: 'primary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.RhomboidsDetailed, percentage: 55, role: 'primary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.LowerTrapezius, percentage: 40, role: 'secondary', citation: 'Scapular depression' },
      { muscle: DetailedMuscle.Infraspinatus, percentage: 35, role: 'secondary', citation: 'External rotation' },
      { muscle: DetailedMuscle.TeresMinor, percentage: 30, role: 'secondary', citation: 'External rotation' },
    ],
    variation: "Both",
  },
  {
    id: "ex22",
    name: "Concentration Curl",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Biceps, percentage: 90 },
        { muscle: Muscle.Forearms, percentage: 10 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 97, role: 'primary', citation: 'ACE Fitness Study; Boeckh-Behrens & Buskies, 2000 (gold standard)' },
      { muscle: DetailedMuscle.Brachialis, percentage: 65, role: 'secondary', citation: 'Elbow flexion synergist' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 30, role: 'secondary', citation: 'Forearm activation' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 10, role: 'stabilizer', citation: 'Grip stabilization' },
    ],
    variation: "A",
  },
  {
    id: "ex23",
    name: "Shoulder Shrugs",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [{ muscle: Muscle.Trapezius, percentage: 95 }],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.UpperTrapezius, percentage: 85, role: 'primary', citation: 'Estimated from shrug mechanics' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 50, role: 'secondary', citation: 'Scapular elevation support' },
      { muscle: DetailedMuscle.LevatorScapulae, percentage: 45, role: 'secondary', citation: 'Scapular elevation' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 15, role: 'stabilizer', citation: 'Grip strength' },
    ],
    variation: "Both",
  },
  {
    id: "ex25",
    name: "Incline Hammer Curl",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Biceps, percentage: 85 },
        { muscle: Muscle.Forearms, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 75, role: 'primary', citation: 'Boeckh-Behrens & Buskies, 2000' },
      { muscle: DetailedMuscle.Brachialis, percentage: 70, role: 'primary', citation: 'Boeckh-Behrens & Buskies, 2000 (enhanced with hammer grip)' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 55, role: 'secondary', citation: 'Boeckh-Behrens & Buskies, 2000 (enhanced with hammer grip)' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 20, role: 'stabilizer', citation: 'Neutral grip stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex26",
    name: "Neutral Grip Pull-ups",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 80 },
        { muscle: Muscle.Biceps, percentage: 35 },
        { muscle: Muscle.Rhomboids, percentage: 25 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 123, role: 'primary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 87, role: 'primary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.Brachialis, percentage: 75, role: 'primary', citation: 'Enhanced with neutral grip' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 37, role: 'secondary', citation: 'Dickie et al., 2017' },
      { muscle: DetailedMuscle.LowerTrapezius, percentage: 50, role: 'secondary', citation: 'Scapular depression' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 35, role: 'secondary', citation: 'Neutral grip forearm activation' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 25, role: 'secondary', citation: 'Grip strength' },
    ],
    variation: "Both",
  },
  {
    id: "ex28",
    name: "Renegade Rows",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 65 },
        { muscle: Muscle.Core, percentage: 50 },
        { muscle: Muscle.Rhomboids, percentage: 35 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 60, role: 'primary', citation: 'Rowing mechanics' },
      { muscle: DetailedMuscle.RhomboidsDetailed, percentage: 50, role: 'primary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 65, role: 'primary', citation: 'Anti-rotation core activation' },
      { muscle: DetailedMuscle.ExternalObliques, percentage: 70, role: 'primary', citation: 'Anti-rotation core activation' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 70, role: 'primary', citation: 'Anti-rotation core activation' },
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 40, role: 'secondary', citation: 'Isometric plank hold' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 40, role: 'secondary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 30, role: 'secondary', citation: 'Elbow flexion' },
    ],
    variation: "Both",
  },
  {
    id: "ex41",
    name: "TRX Pull-up",
    category: "Pull",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 80 },
        { muscle: Muscle.Biceps, percentage: 30 },
        { muscle: Muscle.Rhomboids, percentage: 25 },
        { muscle: Muscle.Core, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 120, role: 'primary', citation: 'TRX pull-up estimated (similar to standard)' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 85, role: 'primary', citation: 'Elbow flexion' },
      { muscle: DetailedMuscle.Brachialis, percentage: 70, role: 'primary', citation: 'Elbow flexion synergist' },
      { muscle: DetailedMuscle.Infraspinatus, percentage: 60, role: 'secondary', citation: 'Rotator cuff engagement' },
      { muscle: DetailedMuscle.LowerTrapezius, percentage: 50, role: 'secondary', citation: 'Scapular depression' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 25, role: 'stabilizer', citation: 'Enhanced core activation vs standard' },
      { muscle: DetailedMuscle.Brachioradialis, percentage: 30, role: 'secondary', citation: 'Forearm activation' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 30, role: 'secondary', citation: 'Increased grip demands' },
    ],
    variation: "Both",
  },
  {
    id: "ex42",
    name: "Wide Grip Pull-ups",
    category: "Pull",
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Lats, percentage: 90 },
        { muscle: Muscle.Biceps, percentage: 25 },
        { muscle: Muscle.Rhomboids, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 123, role: 'primary', citation: 'Youdas et al., 2010' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 60, role: 'primary', citation: 'Dickie et al., 2017 (60.1% MVIC peak)' },
      { muscle: DetailedMuscle.BicepsBrachii, percentage: 70, role: 'primary', citation: 'Lower than standard grip' },
      { muscle: DetailedMuscle.Brachialis, percentage: 60, role: 'secondary', citation: 'Elbow flexion synergist' },
      { muscle: DetailedMuscle.LowerTrapezius, percentage: 50, role: 'secondary', citation: 'Scapular depression' },
      { muscle: DetailedMuscle.Infraspinatus, percentage: 65, role: 'secondary', citation: 'Rotator cuff stabilization' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 25, role: 'secondary', citation: 'Grip strength' },
    ],
    variation: "A",
  },
  // NEW PUSH
  {
    id: "ex29",
    name: "TRX Reverse Flys",
    category: "Push",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Deltoids, percentage: 75 },
        { muscle: Muscle.Rhomboids, percentage: 40 },
        { muscle: Muscle.Trapezius, percentage: 25 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PosteriorDeltoid, percentage: 75, role: 'primary', citation: 'TRX suspension research' },
      { muscle: DetailedMuscle.RhomboidsDetailed, percentage: 40, role: 'secondary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.MiddleTrapezius, percentage: 30, role: 'secondary', citation: 'Scapular retraction' },
      { muscle: DetailedMuscle.Infraspinatus, percentage: 20, role: 'stabilizer', citation: 'Rotator cuff stabilization' },
      { muscle: DetailedMuscle.TeresMinor, percentage: 20, role: 'stabilizer', citation: 'Rotator cuff stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex30",
    name: "Tricep Extension",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [{ muscle: Muscle.Triceps, percentage: 95 }],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 81, role: 'primary', citation: 'ACE Fitness Study, Porcari et al.' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 72, role: 'primary', citation: 'ACE Fitness Study, Porcari et al.' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 67, role: 'primary', citation: 'ACE Fitness Study, Porcari et al.' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 10, role: 'stabilizer', citation: 'Shoulder stabilization' },
    ],
    variation: "A",
  },
  {
    id: "ex40",
    name: "TRX Tricep Extension",
    category: "Push",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
      { muscle: Muscle.Triceps, percentage: 90 },
      { muscle: Muscle.Core, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 75, role: 'primary', citation: 'TRX variation estimated' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 70, role: 'primary', citation: 'TRX variation estimated' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 65, role: 'primary', citation: 'TRX variation estimated' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 20, role: 'stabilizer', citation: 'Core stabilization' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 15, role: 'stabilizer', citation: 'Shoulder stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex31",
    name: "TRX Pushup",
    category: "Push",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 75 },
        { muscle: Muscle.Triceps, percentage: 55 },
        { muscle: Muscle.Deltoids, percentage: 35 },
        { muscle: Muscle.Core, percentage: 25 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 110, role: 'primary', citation: 'TRX suspension research, 2025 (feet suspended)' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 96, role: 'primary', citation: 'TRX suspension research, 2025 (feet suspended)' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 47, role: 'secondary', citation: 'TRX suspension research, 2025' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 42, role: 'secondary', citation: 'TRX suspension research, 2025' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 37, role: 'secondary', citation: 'TRX suspension research, 2025' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 35, role: 'secondary', citation: 'TRX suspension research' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 30, role: 'secondary', citation: 'Enhanced core activation vs standard push-up' },
      { muscle: DetailedMuscle.SerratusAnterior, percentage: 40, role: 'secondary', citation: 'Scapular protraction' },
    ],
    variation: "Both",
  },
  {
    id: "ex32",
    name: "Incline Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 85 },
        { muscle: Muscle.Triceps, percentage: 45 },
        { muscle: Muscle.Deltoids, percentage: 40 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 30, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020 (30° incline optimal)' },
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 70, role: 'primary', citation: 'Rodríguez-Ridao et al., 2020' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 33, role: 'secondary', citation: 'Rodríguez-Ridao et al., 2020 (30-45°)' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 15, role: 'secondary', citation: 'Estimated from pressing mechanics' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 15, role: 'secondary', citation: 'Estimated from pressing mechanics' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 15, role: 'secondary', citation: 'Estimated from pressing mechanics' },
    ],
    variation: "B",
  },
  {
    id: "ex39",
    name: "Single Arm Incline Dumbbell Bench Press",
    category: "Push",
    equipment: "Dumbbells",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 80 },
        { muscle: Muscle.Triceps, percentage: 45 },
        { muscle: Muscle.Deltoids, percentage: 40 },
        { muscle: Muscle.Core, percentage: 30 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 30, role: 'primary', citation: 'Unilateral pressing estimated' },
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 65, role: 'primary', citation: 'Unilateral pressing estimated' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 33, role: 'secondary', citation: 'Unilateral pressing estimated' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 15, role: 'secondary', citation: 'Unilateral pressing estimated' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 15, role: 'secondary', citation: 'Unilateral pressing estimated' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 15, role: 'secondary', citation: 'Unilateral pressing estimated' },
      { muscle: DetailedMuscle.ExternalObliques, percentage: 35, role: 'secondary', citation: 'Anti-rotation core activation' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 35, role: 'secondary', citation: 'Anti-rotation core activation' },
    ],
    variation: "Both",
  },
  {
    id: "ex33",
    name: "Dips",
    category: "Push",
    equipment: "Dip Station",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Triceps, percentage: 80 },
        { muscle: Muscle.Pectoralis, percentage: 50 },
        { muscle: Muscle.Deltoids, percentage: 30 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 88, role: 'primary', citation: 'ACE Study, McKenzie et al., 2022' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 87, role: 'primary', citation: 'ACE Study, McKenzie et al., 2022' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 80, role: 'primary', citation: 'ACE Study, McKenzie et al., 2022' },
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 86, role: 'primary', citation: 'ACE Study, McKenzie et al., 2022' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 73, role: 'primary', citation: 'ACE Study, McKenzie et al., 2022' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 30, role: 'secondary', citation: 'Shoulder involvement estimated' },
    ],
    variation: "B",
  },
  {
    id: "ex34",
    name: "Kettlebell Press",
    category: "Push",
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Deltoids, percentage: 85 },
        { muscle: Muscle.Triceps, percentage: 40 },
        { muscle: Muscle.Core, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 57.9, role: 'primary', citation: 'Saeterbakken et al., 2015' },
      { muscle: DetailedMuscle.MedialDeltoid, percentage: 30, role: 'secondary', citation: 'Estimated from overhead pressing' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 29.5, role: 'secondary', citation: 'Saeterbakken et al., 2015' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 40, role: 'secondary', citation: 'Overhead pressing mechanics' },
      { muscle: DetailedMuscle.TricepsLateralHead, percentage: 40, role: 'secondary', citation: 'Overhead pressing mechanics' },
      { muscle: DetailedMuscle.TricepsMedialHead, percentage: 40, role: 'secondary', citation: 'Overhead pressing mechanics' },
      { muscle: DetailedMuscle.SerratusAnterior, percentage: 25, role: 'secondary', citation: 'Enhanced with bottom-up variation' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 20, role: 'stabilizer', citation: 'Enhanced due to offset loading' },
      { muscle: DetailedMuscle.Supraspinatus, percentage: 15, role: 'stabilizer', citation: 'Rotator cuff stabilization' },
      { muscle: DetailedMuscle.Infraspinatus, percentage: 15, role: 'stabilizer', citation: 'Rotator cuff stabilization' },
    ],
    variation: "Both",
  },
  // NEW LEGS
  {
    id: "ex35",
    name: "Glute Bridges",
    category: "Legs",
    equipment: ["Bodyweight", "Dumbbells"],
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Glutes, percentage: 90 },
        { muscle: Muscle.Hamstrings, percentage: 30 },
        { muscle: Muscle.Core, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.GluteusMaximus, percentage: 75, role: 'primary', citation: 'Hollman et al., 2018 (65-86% MVIC loaded)' },
      { muscle: DetailedMuscle.GluteusMedius, percentage: 40, role: 'secondary', citation: 'Hip stabilization' },
      { muscle: DetailedMuscle.BicepsFemoris, percentage: 25, role: 'secondary', citation: 'Hollman et al., 2018 (16.5-29.8% MVIC)' },
      { muscle: DetailedMuscle.Semitendinosus, percentage: 23, role: 'secondary', citation: 'Medial hamstring activation' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 20, role: 'stabilizer', citation: 'Spinal stabilization' },
    ],
    variation: "B",
  },
  {
    id: "ex36",
    name: "Dumbbell Stiff Legged Deadlift",
    category: "Legs",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Hamstrings, percentage: 90 },
        { muscle: Muscle.Glutes, percentage: 65 },
        { muscle: Muscle.Core, percentage: 25 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.GluteusMaximus, percentage: 70, role: 'primary', citation: 'Coratella et al., 2022 (higher than RDL)' },
      { muscle: DetailedMuscle.BicepsFemoris, percentage: 65, role: 'primary', citation: 'Moderate-high hamstring activation' },
      { muscle: DetailedMuscle.Semitendinosus, percentage: 60, role: 'primary', citation: 'Coratella et al., 2022 (lower than RDL)' },
      { muscle: DetailedMuscle.Semimembranosus, percentage: 60, role: 'primary', citation: 'Medial hamstring activation' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 50, role: 'secondary', citation: 'High spinal loading' },
      { muscle: DetailedMuscle.GluteusMedius, percentage: 30, role: 'stabilizer', citation: 'Hip stabilization' },
    ],
    variation: "B",
  },
  {
    id: "ex37",
    name: "Kettlebell Swings",
    category: "Legs",
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Glutes, percentage: 85 },
        { muscle: Muscle.Hamstrings, percentage: 60 },
        { muscle: Muscle.Core, percentage: 40 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.Semitendinosus, percentage: 115, role: 'primary', citation: 'Lake & Lauder, 2014 (115% MVIC peak in medial hamstrings)' },
      { muscle: DetailedMuscle.Semimembranosus, percentage: 100, role: 'primary', citation: 'High medial hamstring activation' },
      { muscle: DetailedMuscle.BicepsFemoris, percentage: 79, role: 'primary', citation: 'Lake & Lauder, 2014 (78.95% MVIC mean)' },
      { muscle: DetailedMuscle.GluteusMaximus, percentage: 75, role: 'primary', citation: 'Lake & Lauder, 2014 (75.02% MVIC mean)' },
      { muscle: DetailedMuscle.GluteusMedius, percentage: 55, role: 'secondary', citation: 'McGill & Marshall (55.47% MVIC)' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 40, role: 'secondary', citation: 'Core stabilization' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 35, role: 'secondary', citation: 'Spinal stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex43",
    name: "Dumbbell Goblet Squat",
    category: "Legs",
    equipment: "Dumbbells",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Quadriceps, percentage: 85 },
        { muscle: Muscle.Glutes, percentage: 65 },
        { muscle: Muscle.Core, percentage: 30 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.VastusLateralis, percentage: 76.4, role: 'primary', citation: 'Systematic review, 2024 (same as kettlebell)' },
      { muscle: DetailedMuscle.VastusMedialis, percentage: 67.8, role: 'primary', citation: 'Systematic review, 2024 (same as kettlebell)' },
      { muscle: DetailedMuscle.VastusIntermedius, percentage: 65, role: 'primary', citation: 'Estimated from quad mechanics' },
      { muscle: DetailedMuscle.RectusFemoris, percentage: 70, role: 'primary', citation: 'Hip flexor and knee extensor' },
      { muscle: DetailedMuscle.GluteusMaximus, percentage: 65, role: 'primary', citation: 'Estimated moderate-high' },
      { muscle: DetailedMuscle.GluteusMedius, percentage: 40, role: 'secondary', citation: 'Hip stabilization' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 30, role: 'stabilizer', citation: 'Core stabilization' },
      { muscle: DetailedMuscle.ErectorSpinae, percentage: 25, role: 'stabilizer', citation: 'Spinal stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex44",
    name: "Spider Planks",
    category: "Core",
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Core, percentage: 90 },
        { muscle: Muscle.Deltoids, percentage: 20 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.ExternalObliques, percentage: 105, role: 'primary', citation: 'Estimated >100% MVIC (plank + dynamic movement)' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 82, role: 'primary', citation: 'Estimated 75-90% MVIC' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 65, role: 'primary', citation: 'Estimated 50-80% MVIC' },
      { muscle: DetailedMuscle.Iliopsoas, percentage: 60, role: 'secondary', citation: 'Hip flexor engagement from knee drives' },
      { muscle: DetailedMuscle.TransverseAbdominis, percentage: 50, role: 'secondary', citation: 'Deep core stabilization' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 20, role: 'stabilizer', citation: 'Shoulder stabilization' },
    ],
    variation: "Both",
  },
  {
    id: "ex45",
    name: "TRX Mountain Climbers",
    category: "Core",
    equipment: "TRX",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Core, percentage: 85 },
        { muscle: Muscle.Deltoids, percentage: 30 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 70, role: 'primary', citation: 'Estimated >60% MVIC (feet suspended)' },
      { muscle: DetailedMuscle.Iliopsoas, percentage: 75, role: 'primary', citation: 'High hip flexor activation' },
      { muscle: DetailedMuscle.ExternalObliques, percentage: 65, role: 'primary', citation: 'Moderate-high oblique activation' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 60, role: 'secondary', citation: 'Moderate-high oblique activation' },
      { muscle: DetailedMuscle.AnteriorDeltoid, percentage: 30, role: 'stabilizer', citation: 'Enhanced shoulder stabilization vs floor-based' },
    ],
    variation: "Both",
  },
  {
    id: "ex46",
    name: "Hanging Leg Raises",
    category: "Core",
    equipment: "Pull-up Bar",
    difficulty: "Advanced",
    muscleEngagements: [
        { muscle: Muscle.Core, percentage: 95 },
        { muscle: Muscle.Forearms, percentage: 15 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.Iliopsoas, percentage: 95, role: 'primary', citation: 'Very high hip flexor activation' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 85, role: 'primary', citation: 'High abdominal activation' },
      { muscle: DetailedMuscle.ExternalObliques, percentage: 55, role: 'secondary', citation: 'Moderate oblique activation' },
      { muscle: DetailedMuscle.InternalObliques, percentage: 50, role: 'secondary', citation: 'Moderate oblique activation' },
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 30, role: 'stabilizer', citation: 'Lat stabilization during hang' },
      { muscle: DetailedMuscle.WristFlexors, percentage: 20, role: 'stabilizer', citation: 'Grip strength' },
    ],
    variation: "Both",
  },
  {
    id: "ex47",
    name: "Box Step-ups",
    category: "Legs",
    equipment: "Plyo Box",
    difficulty: "Beginner",
    muscleEngagements: [
        { muscle: Muscle.Quadriceps, percentage: 70 },
        { muscle: Muscle.Glutes, percentage: 60 },
        { muscle: Muscle.Hamstrings, percentage: 30 },
        { muscle: Muscle.Calves, percentage: 20 },
        { muscle: Muscle.Core, percentage: 15 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.GluteusMaximus, percentage: 169, role: 'primary', citation: 'Rebuttal et al., 2020 (169.22% MVIC - highest of common exercises)' },
      { muscle: DetailedMuscle.VastusLateralis, percentage: 67, role: 'primary', citation: 'Youdas et al. (62-72% MVIC)' },
      { muscle: DetailedMuscle.RectusFemoris, percentage: 51, role: 'primary', citation: 'Youdas et al. (40-63% MVIC)' },
      { muscle: DetailedMuscle.GluteusMedius, percentage: 70, role: 'primary', citation: 'High hip stabilization during unilateral movement' },
      { muscle: DetailedMuscle.VastusMedialis, percentage: 60, role: 'secondary', citation: 'Quad activation' },
      { muscle: DetailedMuscle.BicepsFemoris, percentage: 30, role: 'secondary', citation: 'Hamstring activation' },
      { muscle: DetailedMuscle.Semitendinosus, percentage: 28, role: 'secondary', citation: 'Medial hamstring activation' },
      { muscle: DetailedMuscle.GastrocnemiusMedial, percentage: 20, role: 'secondary', citation: 'Calf activation during push-off' },
      { muscle: DetailedMuscle.GastrocnemiusLateral, percentage: 20, role: 'secondary', citation: 'Calf activation during push-off' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 15, role: 'stabilizer', citation: 'Core stabilization' },
    ],
    variation: "B",
  },
  {
    id: "ex48",
    name: "Dumbbell Pullover",
    category: "Pull",
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    muscleEngagements: [
        { muscle: Muscle.Pectoralis, percentage: 65 },
        { muscle: Muscle.Lats, percentage: 60 },
        { muscle: Muscle.Deltoids, percentage: 50 },
        { muscle: Muscle.Triceps, percentage: 25 },
        { muscle: Muscle.Core, percentage: 15 },
    ],
    detailedMuscleEngagements: [
      { muscle: DetailedMuscle.LatissimusDorsi, percentage: 60, role: 'primary', citation: 'Lat-focused variation in stretched position' },
      { muscle: DetailedMuscle.PectoralisMajorSternal, percentage: 55, role: 'primary', citation: 'Sternal head engagement' },
      { muscle: DetailedMuscle.PectoralisMajorClavicular, percentage: 40, role: 'secondary', citation: 'Clavicular head engagement' },
      { muscle: DetailedMuscle.SerratusAnterior, percentage: 45, role: 'secondary', citation: 'Scapular protraction' },
      { muscle: DetailedMuscle.TricepsLongHead, percentage: 35, role: 'secondary', citation: 'Long head stretch position' },
      { muscle: DetailedMuscle.PosteriorDeltoid, percentage: 30, role: 'secondary', citation: 'Shoulder extension' },
      { muscle: DetailedMuscle.RectusAbdominis, percentage: 15, role: 'stabilizer', citation: 'Core stabilization' },
    ],
    variation: "Both",
  },
];

export function getExerciseByName(name: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find(ex => ex.name === name);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find(ex => ex.id === id);
}

// ============================================
// WORKOUT ROTATION SEQUENCE
// ============================================

import { RotationSequenceItem } from './types';

/**
 * Defines the user's workout rotation sequence:
 * Push A → Legs A → [rest] → Pull A → [rest] → Push B → Legs B → [rest] → Pull B → [cycle repeats]
 *
 * Pattern: 2 days on, 1 day off, 1 day on, 1 day off (repeating)
 * Rule: Never more than 5 days before hitting same muscle group again
 * Core workouts are optional and don't advance the rotation phase
 */
export const ROTATION_SEQUENCE: RotationSequenceItem[] = [
  { category: 'Push', variation: 'A', restAfter: 0 },  // Day 1
  { category: 'Legs', variation: 'A', restAfter: 1 },  // Day 2 → rest on Day 3
  { category: 'Pull', variation: 'A', restAfter: 1 },  // Day 4 → rest on Day 5 (or Core)
  { category: 'Push', variation: 'B', restAfter: 0 },  // Day 6
  { category: 'Legs', variation: 'B', restAfter: 1 },  // Day 7 → rest on Day 8
  { category: 'Pull', variation: 'B', restAfter: 0 },  // Day 9 → cycle repeats
];
